// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.27.0
// source: tesla.proto

package powerwall

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Format int32

const (
	Format_None Format = 0
	Format_Raw  Format = 1
	Format_Json Format = 2
)

// Enum value maps for Format.
var (
	Format_name = map[int32]string{
		0: "None",
		1: "Raw",
		2: "Json",
	}
	Format_value = map[string]int32{
		"None": 0,
		"Raw":  1,
		"Json": 2,
	}
)

func (x Format) Enum() *Format {
	p := new(Format)
	*p = x
	return p
}

func (x Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Format) Descriptor() protoreflect.EnumDescriptor {
	return file_tesla_proto_enumTypes[0].Descriptor()
}

func (Format) Type() protoreflect.EnumType {
	return &file_tesla_proto_enumTypes[0]
}

func (x Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Format.Descriptor instead.
func (Format) EnumDescriptor() ([]byte, []int) {
	return file_tesla_proto_rawDescGZIP(), []int{0}
}

type ParentMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message *MessageEnvelope `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Tail    *Tail            `protobuf:"bytes,2,opt,name=tail,proto3" json:"tail,omitempty"`
}

func (x *ParentMessage) Reset() {
	*x = ParentMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tesla_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParentMessage) ProtoMessage() {}

func (x *ParentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tesla_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParentMessage.ProtoReflect.Descriptor instead.
func (*ParentMessage) Descriptor() ([]byte, []int) {
	return file_tesla_proto_rawDescGZIP(), []int{0}
}

func (x *ParentMessage) GetMessage() *MessageEnvelope {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ParentMessage) GetTail() *Tail {
	if x != nil {
		return x.Tail
	}
	return nil
}

type MessageEnvelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeliveryChannel int32        `protobuf:"varint,1,opt,name=deliveryChannel,proto3" json:"deliveryChannel,omitempty"`
	Sender          *Participant `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient       *Participant `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Config          *ConfigType  `protobuf:"bytes,15,opt,name=config,proto3,oneof" json:"config,omitempty"`
	Payload         *QueryType   `protobuf:"bytes,16,opt,name=payload,proto3,oneof" json:"payload,omitempty"`
}

func (x *MessageEnvelope) Reset() {
	*x = MessageEnvelope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tesla_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEnvelope) ProtoMessage() {}

func (x *MessageEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_tesla_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEnvelope.ProtoReflect.Descriptor instead.
func (*MessageEnvelope) Descriptor() ([]byte, []int) {
	return file_tesla_proto_rawDescGZIP(), []int{1}
}

func (x *MessageEnvelope) GetDeliveryChannel() int32 {
	if x != nil {
		return x.DeliveryChannel
	}
	return 0
}

func (x *MessageEnvelope) GetSender() *Participant {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *MessageEnvelope) GetRecipient() *Participant {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *MessageEnvelope) GetConfig() *ConfigType {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *MessageEnvelope) GetPayload() *QueryType {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Participant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Id:
	//
	//	*Participant_Din
	//	*Participant_TeslaService
	//	*Participant_Local
	//	*Participant_AuthorizedClient
	Id isParticipant_Id `protobuf_oneof:"id"`
}

func (x *Participant) Reset() {
	*x = Participant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tesla_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Participant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Participant) ProtoMessage() {}

func (x *Participant) ProtoReflect() protoreflect.Message {
	mi := &file_tesla_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Participant.ProtoReflect.Descriptor instead.
func (*Participant) Descriptor() ([]byte, []int) {
	return file_tesla_proto_rawDescGZIP(), []int{2}
}

func (m *Participant) GetId() isParticipant_Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (x *Participant) GetDin() string {
	if x, ok := x.GetId().(*Participant_Din); ok {
		return x.Din
	}
	return ""
}

func (x *Participant) GetTeslaService() int32 {
	if x, ok := x.GetId().(*Participant_TeslaService); ok {
		return x.TeslaService
	}
	return 0
}

func (x *Participant) GetLocal() int32 {
	if x, ok := x.GetId().(*Participant_Local); ok {
		return x.Local
	}
	return 0
}

func (x *Participant) GetAuthorizedClient() int32 {
	if x, ok := x.GetId().(*Participant_AuthorizedClient); ok {
		return x.AuthorizedClient
	}
	return 0
}

type isParticipant_Id interface {
	isParticipant_Id()
}

type Participant_Din struct {
	Din string `protobuf:"bytes,1,opt,name=din,proto3,oneof"`
}

type Participant_TeslaService struct {
	TeslaService int32 `protobuf:"varint,2,opt,name=teslaService,proto3,oneof"`
}

type Participant_Local struct {
	Local int32 `protobuf:"varint,3,opt,name=local,proto3,oneof"`
}

type Participant_AuthorizedClient struct {
	AuthorizedClient int32 `protobuf:"varint,4,opt,name=authorizedClient,proto3,oneof"`
}

func (*Participant_Din) isParticipant_Id() {}

func (*Participant_TeslaService) isParticipant_Id() {}

func (*Participant_Local) isParticipant_Id() {}

func (*Participant_AuthorizedClient) isParticipant_Id() {}

type Tail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Tail) Reset() {
	*x = Tail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tesla_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tail) ProtoMessage() {}

func (x *Tail) ProtoReflect() protoreflect.Message {
	mi := &file_tesla_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tail.ProtoReflect.Descriptor instead.
func (*Tail) Descriptor() ([]byte, []int) {
	return file_tesla_proto_rawDescGZIP(), []int{3}
}

func (x *Tail) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type QueryType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Send *PayloadQuerySend `protobuf:"bytes,1,opt,name=send,proto3,oneof" json:"send,omitempty"`
	Recv *PayloadString    `protobuf:"bytes,2,opt,name=recv,proto3,oneof" json:"recv,omitempty"`
}

func (x *QueryType) Reset() {
	*x = QueryType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tesla_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryType) ProtoMessage() {}

func (x *QueryType) ProtoReflect() protoreflect.Message {
	mi := &file_tesla_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryType.ProtoReflect.Descriptor instead.
func (*QueryType) Descriptor() ([]byte, []int) {
	return file_tesla_proto_rawDescGZIP(), []int{4}
}

func (x *QueryType) GetSend() *PayloadQuerySend {
	if x != nil {
		return x.Send
	}
	return nil
}

func (x *QueryType) GetRecv() *PayloadString {
	if x != nil {
		return x.Recv
	}
	return nil
}

type PayloadQuerySend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestFormat Format         `protobuf:"varint,1,opt,name=requestFormat,proto3,enum=tedapi.Format" json:"requestFormat,omitempty"`
	Payload       *PayloadString `protobuf:"bytes,2,opt,name=payload,proto3,oneof" json:"payload,omitempty"`
	Signature     []byte         `protobuf:"bytes,3,opt,name=signature,proto3,oneof" json:"signature,omitempty"`
	Body          *StringValue   `protobuf:"bytes,4,opt,name=body,proto3,oneof" json:"body,omitempty"`
}

func (x *PayloadQuerySend) Reset() {
	*x = PayloadQuerySend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tesla_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayloadQuerySend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadQuerySend) ProtoMessage() {}

func (x *PayloadQuerySend) ProtoReflect() protoreflect.Message {
	mi := &file_tesla_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadQuerySend.ProtoReflect.Descriptor instead.
func (*PayloadQuerySend) Descriptor() ([]byte, []int) {
	return file_tesla_proto_rawDescGZIP(), []int{5}
}

func (x *PayloadQuerySend) GetRequestFormat() Format {
	if x != nil {
		return x.RequestFormat
	}
	return Format_None
}

func (x *PayloadQuerySend) GetPayload() *PayloadString {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PayloadQuerySend) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *PayloadQuerySend) GetBody() *StringValue {
	if x != nil {
		return x.Body
	}
	return nil
}

type ConfigType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Config:
	//
	//	*ConfigType_Send
	//	*ConfigType_Recv
	Config isConfigType_Config `protobuf_oneof:"config"`
}

func (x *ConfigType) Reset() {
	*x = ConfigType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tesla_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigType) ProtoMessage() {}

func (x *ConfigType) ProtoReflect() protoreflect.Message {
	mi := &file_tesla_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigType.ProtoReflect.Descriptor instead.
func (*ConfigType) Descriptor() ([]byte, []int) {
	return file_tesla_proto_rawDescGZIP(), []int{6}
}

func (m *ConfigType) GetConfig() isConfigType_Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (x *ConfigType) GetSend() *PayloadConfigSend {
	if x, ok := x.GetConfig().(*ConfigType_Send); ok {
		return x.Send
	}
	return nil
}

func (x *ConfigType) GetRecv() *PayloadConfigRecv {
	if x, ok := x.GetConfig().(*ConfigType_Recv); ok {
		return x.Recv
	}
	return nil
}

type isConfigType_Config interface {
	isConfigType_Config()
}

type ConfigType_Send struct {
	Send *PayloadConfigSend `protobuf:"bytes,1,opt,name=send,proto3,oneof"`
}

type ConfigType_Recv struct {
	Recv *PayloadConfigRecv `protobuf:"bytes,2,opt,name=recv,proto3,oneof"`
}

func (*ConfigType_Send) isConfigType_Config() {}

func (*ConfigType_Recv) isConfigType_Config() {}

type PayloadConfigSend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num  int32  `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	File string `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *PayloadConfigSend) Reset() {
	*x = PayloadConfigSend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tesla_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayloadConfigSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadConfigSend) ProtoMessage() {}

func (x *PayloadConfigSend) ProtoReflect() protoreflect.Message {
	mi := &file_tesla_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadConfigSend.ProtoReflect.Descriptor instead.
func (*PayloadConfigSend) Descriptor() ([]byte, []int) {
	return file_tesla_proto_rawDescGZIP(), []int{7}
}

func (x *PayloadConfigSend) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *PayloadConfigSend) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

type PayloadConfigRecv struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File *ConfigString `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Code []byte        `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *PayloadConfigRecv) Reset() {
	*x = PayloadConfigRecv{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tesla_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayloadConfigRecv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadConfigRecv) ProtoMessage() {}

func (x *PayloadConfigRecv) ProtoReflect() protoreflect.Message {
	mi := &file_tesla_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadConfigRecv.ProtoReflect.Descriptor instead.
func (*PayloadConfigRecv) Descriptor() ([]byte, []int) {
	return file_tesla_proto_rawDescGZIP(), []int{8}
}

func (x *PayloadConfigRecv) GetFile() *ConfigString {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *PayloadConfigRecv) GetCode() []byte {
	if x != nil {
		return x.Code
	}
	return nil
}

type ConfigString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Text string `protobuf:"bytes,100,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *ConfigString) Reset() {
	*x = ConfigString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tesla_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigString) ProtoMessage() {}

func (x *ConfigString) ProtoReflect() protoreflect.Message {
	mi := &file_tesla_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigString.ProtoReflect.Descriptor instead.
func (*ConfigString) Descriptor() ([]byte, []int) {
	return file_tesla_proto_rawDescGZIP(), []int{9}
}

func (x *ConfigString) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigString) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type PayloadString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Text  string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *PayloadString) Reset() {
	*x = PayloadString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tesla_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayloadString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadString) ProtoMessage() {}

func (x *PayloadString) ProtoReflect() protoreflect.Message {
	mi := &file_tesla_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadString.ProtoReflect.Descriptor instead.
func (*PayloadString) Descriptor() ([]byte, []int) {
	return file_tesla_proto_rawDescGZIP(), []int{10}
}

func (x *PayloadString) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *PayloadString) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type StringValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *StringValue) Reset() {
	*x = StringValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tesla_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringValue) ProtoMessage() {}

func (x *StringValue) ProtoReflect() protoreflect.Message {
	mi := &file_tesla_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringValue.ProtoReflect.Descriptor instead.
func (*StringValue) Descriptor() ([]byte, []int) {
	return file_tesla_proto_rawDescGZIP(), []int{11}
}

func (x *StringValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_tesla_proto protoreflect.FileDescriptor

var file_tesla_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x74, 0x65, 0x73, 0x6c, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x74,
	0x65, 0x64, 0x61, 0x70, 0x69, 0x22, 0x64, 0x0a, 0x0d, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x31, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x74, 0x65, 0x64, 0x61, 0x70, 0x69,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x74, 0x61, 0x69,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x74, 0x65, 0x64, 0x61, 0x70, 0x69,
	0x2e, 0x54, 0x61, 0x69, 0x6c, 0x52, 0x04, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x95, 0x02, 0x0a, 0x0f,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12,
	0x28, 0x0a, 0x0f, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65,
	0x72, 0x79, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x2b, 0x0a, 0x06, 0x73, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x65, 0x64, 0x61,
	0x70, 0x69, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x52, 0x06,
	0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69,
	0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x65, 0x64, 0x61,
	0x70, 0x69, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x52, 0x09,
	0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x2f, 0x0a, 0x06, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x74, 0x65, 0x64, 0x61,
	0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52,
	0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x88, 0x01, 0x01, 0x12, 0x30, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x65,
	0x64, 0x61, 0x70, 0x69, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x48, 0x01,
	0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07,
	0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x22, 0x93, 0x01, 0x0a, 0x0b, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70,
	0x61, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x03, 0x64, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x03, 0x64, 0x69, 0x6e, 0x12, 0x24, 0x0a, 0x0c, 0x74, 0x65, 0x73, 0x6c, 0x61,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52,
	0x0c, 0x74, 0x65, 0x73, 0x6c, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a,
	0x05, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x05,
	0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x12, 0x2c, 0x0a, 0x10, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69,
	0x7a, 0x65, 0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x48,
	0x00, 0x52, 0x10, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x42, 0x04, 0x0a, 0x02, 0x69, 0x64, 0x22, 0x1c, 0x0a, 0x04, 0x54, 0x61, 0x69,
	0x6c, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x80, 0x01, 0x0a, 0x09, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x31, 0x0a, 0x04, 0x73, 0x65, 0x6e, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x74, 0x65, 0x64, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x65, 0x6e, 0x64, 0x48, 0x00, 0x52,
	0x04, 0x73, 0x65, 0x6e, 0x64, 0x88, 0x01, 0x01, 0x12, 0x2e, 0x0a, 0x04, 0x72, 0x65, 0x63, 0x76,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x65, 0x64, 0x61, 0x70, 0x69, 0x2e,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x48, 0x01, 0x52,
	0x04, 0x72, 0x65, 0x63, 0x76, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x73, 0x65, 0x6e,
	0x64, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x72, 0x65, 0x63, 0x76, 0x22, 0xf2, 0x01, 0x0a, 0x10, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x65, 0x6e, 0x64, 0x12,
	0x34, 0x0a, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x74, 0x65, 0x64, 0x61, 0x70, 0x69, 0x2e,
	0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x52, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x34, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x65, 0x64, 0x61, 0x70, 0x69, 0x2e,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x88, 0x01, 0x01, 0x12, 0x21, 0x0a, 0x09, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x01,
	0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x88, 0x01, 0x01, 0x12, 0x2c,
	0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74,
	0x65, 0x64, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x48, 0x02, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08,
	0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x22,
	0x78, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2f, 0x0a,
	0x04, 0x73, 0x65, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x74, 0x65,
	0x64, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x53, 0x65, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x04, 0x73, 0x65, 0x6e, 0x64, 0x12, 0x2f,
	0x0a, 0x04, 0x72, 0x65, 0x63, 0x76, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x74,
	0x65, 0x64, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x65, 0x63, 0x76, 0x48, 0x00, 0x52, 0x04, 0x72, 0x65, 0x63, 0x76, 0x42,
	0x08, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x39, 0x0a, 0x11, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d,
	0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x66, 0x69, 0x6c, 0x65, 0x22, 0x51, 0x0a, 0x11, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x63, 0x76, 0x12, 0x28, 0x0a, 0x04, 0x66, 0x69, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x65, 0x64, 0x61, 0x70, 0x69,
	0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x04, 0x66,
	0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x36, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x18, 0x64, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22,
	0x39, 0x0a, 0x0d, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x23, 0x0a, 0x0b, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2a,
	0x25, 0x0a, 0x06, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e,
	0x65, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x61, 0x77, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04,
	0x4a, 0x73, 0x6f, 0x6e, 0x10, 0x02, 0x42, 0x14, 0x5a, 0x12, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x77, 0x61, 0x6c, 0x6c, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tesla_proto_rawDescOnce sync.Once
	file_tesla_proto_rawDescData = file_tesla_proto_rawDesc
)

func file_tesla_proto_rawDescGZIP() []byte {
	file_tesla_proto_rawDescOnce.Do(func() {
		file_tesla_proto_rawDescData = protoimpl.X.CompressGZIP(file_tesla_proto_rawDescData)
	})
	return file_tesla_proto_rawDescData
}

var file_tesla_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tesla_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_tesla_proto_goTypes = []interface{}{
	(Format)(0),               // 0: tedapi.Format
	(*ParentMessage)(nil),     // 1: tedapi.ParentMessage
	(*MessageEnvelope)(nil),   // 2: tedapi.MessageEnvelope
	(*Participant)(nil),       // 3: tedapi.Participant
	(*Tail)(nil),              // 4: tedapi.Tail
	(*QueryType)(nil),         // 5: tedapi.QueryType
	(*PayloadQuerySend)(nil),  // 6: tedapi.PayloadQuerySend
	(*ConfigType)(nil),        // 7: tedapi.ConfigType
	(*PayloadConfigSend)(nil), // 8: tedapi.PayloadConfigSend
	(*PayloadConfigRecv)(nil), // 9: tedapi.PayloadConfigRecv
	(*ConfigString)(nil),      // 10: tedapi.ConfigString
	(*PayloadString)(nil),     // 11: tedapi.PayloadString
	(*StringValue)(nil),       // 12: tedapi.StringValue
}
var file_tesla_proto_depIdxs = []int32{
	2,  // 0: tedapi.ParentMessage.message:type_name -> tedapi.MessageEnvelope
	4,  // 1: tedapi.ParentMessage.tail:type_name -> tedapi.Tail
	3,  // 2: tedapi.MessageEnvelope.sender:type_name -> tedapi.Participant
	3,  // 3: tedapi.MessageEnvelope.recipient:type_name -> tedapi.Participant
	7,  // 4: tedapi.MessageEnvelope.config:type_name -> tedapi.ConfigType
	5,  // 5: tedapi.MessageEnvelope.payload:type_name -> tedapi.QueryType
	6,  // 6: tedapi.QueryType.send:type_name -> tedapi.PayloadQuerySend
	11, // 7: tedapi.QueryType.recv:type_name -> tedapi.PayloadString
	0,  // 8: tedapi.PayloadQuerySend.requestFormat:type_name -> tedapi.Format
	11, // 9: tedapi.PayloadQuerySend.payload:type_name -> tedapi.PayloadString
	12, // 10: tedapi.PayloadQuerySend.body:type_name -> tedapi.StringValue
	8,  // 11: tedapi.ConfigType.send:type_name -> tedapi.PayloadConfigSend
	9,  // 12: tedapi.ConfigType.recv:type_name -> tedapi.PayloadConfigRecv
	10, // 13: tedapi.PayloadConfigRecv.file:type_name -> tedapi.ConfigString
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_tesla_proto_init() }
func file_tesla_proto_init() {
	if File_tesla_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tesla_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParentMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tesla_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageEnvelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tesla_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Participant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tesla_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tesla_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tesla_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayloadQuerySend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tesla_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tesla_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayloadConfigSend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tesla_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayloadConfigRecv); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tesla_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tesla_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayloadString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tesla_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_tesla_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_tesla_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Participant_Din)(nil),
		(*Participant_TeslaService)(nil),
		(*Participant_Local)(nil),
		(*Participant_AuthorizedClient)(nil),
	}
	file_tesla_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_tesla_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_tesla_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*ConfigType_Send)(nil),
		(*ConfigType_Recv)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tesla_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tesla_proto_goTypes,
		DependencyIndexes: file_tesla_proto_depIdxs,
		EnumInfos:         file_tesla_proto_enumTypes,
		MessageInfos:      file_tesla_proto_msgTypes,
	}.Build()
	File_tesla_proto = out.File
	file_tesla_proto_rawDesc = nil
	file_tesla_proto_goTypes = nil
	file_tesla_proto_depIdxs = nil
}
